-- Tabela para registrar as ordens executadas na Binance
CREATE TABLE IF NOT EXISTS `orders` (
  `idx` int NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `created_by` int NOT NULL,
  `modified_at` datetime DEFAULT NULL,
  `modified_by` int DEFAULT NULL,
  `removed_at` datetime DEFAULT NULL,
  `removed_by` int DEFAULT NULL,
  `active` enum('yes','no') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `binance_order_id` bigint NOT NULL COMMENT 'ID da ordem na Binance',
  `binance_client_order_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Client Order ID',
  `symbol` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Par de trading',
  `side` enum('BUY','SELL') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Lado da ordem',
  `type` enum('MARKET','LIMIT') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Tipo da ordem',
  `order_type` enum('entry','take_profit') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Finalidade da ordem',
  `price` decimal(20,8) DEFAULT NULL COMMENT 'Preço (para LIMIT)',
  `quantity` decimal(20,8) NOT NULL COMMENT 'Quantidade',
  `executed_qty` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Quantidade executada',
  `status` enum('NEW','PARTIALLY_FILLED','FILLED','CANCELED','REJECTED','EXPIRED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NEW',
  `cumulative_quote_qty` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Valor total executado',
  `order_created_at` bigint DEFAULT NULL COMMENT 'Timestamp Binance (ms)',
  `order_updated_at` bigint DEFAULT NULL COMMENT 'Última atualização Binance (ms)',
  `api_response` json DEFAULT NULL COMMENT 'Response completo da API Binance',
  PRIMARY KEY (`idx`),
  KEY `idx_binance_order_id` (`binance_order_id`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_status` (`status`),
  KEY `idx_order_type` (`order_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ordens individuais executadas na Binance';