-- Tabela para registrar os trades executados
CREATE TABLE IF NOT EXISTS `trades` (
  `idx` int NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `created_by` int NOT NULL,
  `modified_at` datetime DEFAULT NULL,
  `modified_by` int DEFAULT NULL,
  `removed_at` datetime DEFAULT NULL,
  `removed_by` int DEFAULT NULL,
  `active` enum('yes','no') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes',
  `symbol` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Par de trading (ex: BTCUSDC)',
  `status` enum('open','closed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open' COMMENT 'Status do trade',
  `entry_price` decimal(20,8) NOT NULL COMMENT 'Preço de entrada',
  `quantity` decimal(20,8) NOT NULL COMMENT 'Quantidade comprada',
  `investment` decimal(20,8) NOT NULL COMMENT 'Valor investido em USDC',
  `strategy` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'bollinger_bands' COMMENT 'Estratégia utilizada',
  `timeframe` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '15m' COMMENT 'Timeframe analisado',
  `bb_upper` decimal(20,8) DEFAULT NULL COMMENT 'Banda superior',
  `bb_middle` decimal(20,8) DEFAULT NULL COMMENT 'Banda média',
  `bb_lower` decimal(20,8) DEFAULT NULL COMMENT 'Banda inferior',
  `take_profit_price` decimal(20,8) DEFAULT NULL COMMENT 'Preço de take profit (legado)',
  `take_profit_1_price` decimal(20,8) DEFAULT NULL COMMENT 'Preço de take profit 1 (alvo conservador)',
  `take_profit_2_price` decimal(20,8) DEFAULT NULL COMMENT 'Preço de take profit 2 (alvo agressivo)',
  `tp1_status` enum('pending','partially_filled','filled','cancelled') COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT 'Status TP1',
  `tp2_status` enum('pending','partially_filled','filled','cancelled') COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT 'Status TP2',
  `tp1_executed_qty` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Quantidade executada em TP1',
  `tp2_executed_qty` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Quantidade executada em TP2',
  `exit_price` decimal(20,8) DEFAULT NULL COMMENT 'Preço de saída',
  `exit_type` enum('take_profit','manual') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Tipo de saída',
  `profit_loss` decimal(20,8) DEFAULT NULL COMMENT 'Lucro/Prejuízo em USDC',
  `profit_loss_percent` decimal(10,4) DEFAULT NULL COMMENT 'Lucro/Prejuízo em %',
  `opened_at` datetime NOT NULL COMMENT 'Data/hora de abertura',
  `closed_at` datetime DEFAULT NULL COMMENT 'Data/hora de fechamento',
  `notes` text COLLATE utf8mb4_unicode_ci COMMENT 'Observações adicionais',
  PRIMARY KEY (`idx`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_status` (`status`),
  KEY `idx_opened_at` (`opened_at`),
  KEY `idx_closed_at` (`closed_at`),
  KEY `idx_active` (`active`),
  KEY `idx_tp1_status` (`tp1_status`),
  KEY `idx_tp2_status` (`tp2_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Trades executados pelo bot';